# Generated by Django 3.2.9 on 2021-11-29 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('small_description', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='technology/')),
                ('description', models.TextField(null=True)),
                ('month_of_event', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], default='Jan', max_length=30)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('type_of_event', models.CharField(choices=[('soon', 'soon'), ('att', 'att'), ('imp', 'imp')], default='soon', max_length=30)),
            ],
        ),
    ]
