# Generated by Django 3.2.9 on 2021-11-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='value',
            new_name='date',
        ),
    ]
