# Generated by Django 3.2.9 on 2021-11-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_value_technology_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='SuperviserContact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='SuperviserEmail',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='SuperviserName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='VenueName',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='day_of_event',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AddField(
            model_name='technology',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
