# Generated by Django 3.2.9 on 2021-12-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20211204_2149'),
        ('event', '0009_auto_20211204_2151'),
    ]

    operations = [
    ]
