# Generated by Django 3.2.9 on 2021-12-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20211206_0118'),
        ('event', '0010_merge_0009_auto_20211204_2149_0009_auto_20211204_2151'),
    ]

    operations = [
    ]
