# Generated by Django 3.2.5 on 2021-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20211207_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='dates',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='dates',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentwelfare',
            name='dates',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='dates',
            field=models.DateField(null=True),
        ),
    ]
