# Generated by Django 2.2.9 on 2022-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20220123_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gold', models.CharField(max_length=100)),
                ('silver', models.CharField(max_length=100)),
                ('bronze', models.CharField(max_length=100)),
            ],
        ),
    ]
