# Generated by Django 2.2.9 on 2021-12-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSGhackathon', '0004_achivement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('SocialCulture', 'SocialCulture'), ('SportsGames', 'SportsGames'), ('StudentWelfare', 'StudentWelfare'), ('Others', 'Others')], default='Technology', max_length=30),
        ),
    ]
