# Generated by Django 2.2.9 on 2021-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSGhackathon', '0005_auto_20211221_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Social_Culture', 'Social_Culture'), ('Sports_Games', 'Sports_Games'), ('Student_Welfare', 'Student_Welfare'), ('Others', 'Others')], default='Technology', max_length=30),
        ),
    ]
