# Generated by Django 2.2.9 on 2021-12-22 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TSGhackathon', '0006_auto_20211221_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivement',
            name='photo',
        ),
        migrations.AddField(
            model_name='achivement',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='student/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achivement',
            name='type_of_event',
            field=models.CharField(choices=[('tech', 'tech'), ('soc', 'soc'), ('spg', 'spg'), ('stw', 'stw'), ('ot', 'ot')], default='soon', max_length=30),
        ),
    ]
