# Generated by Django 2.2.9 on 2021-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSGhackathon', '0008_auto_20211222_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='type_of_event',
            field=models.CharField(choices=[('tech', 'tech'), ('soc', 'soc'), ('spg', 'spg'), ('stw', 'stw'), ('ot', 'ot')], default='tech', max_length=30),
        ),
    ]
